window.XplainSeed = {
  version: 9,
  organizations: [
    {
      id: "org-gvi",
      name: "Green Valley International",
      domains: ["greenvalley.edu"],
      logo_data_url: null,
      created_at: "2026-06-01T09:00:00Z",
    },
    {
      id: "org-inventors",
      name: "Inventors Academy",
      domains: ["inventors.academy"],
      logo_data_url: null,
      created_at: "2026-06-15T09:00:00Z",
    },
  ],
  users: [
    {
      id: "t-salma",
      name: "Ms. Salma",
      email: "salma@greenvalley.edu",
      password: "teacher123",
      phone: "+1 555 0101",
      role: "teacher",
      organization_id: "org-gvi",
      status: "active",
      locale: "en",
      default_identity_id: "id-gvi-clean",
      created_at: "2026-06-02T09:00:00Z",
    },
    {
      id: "t-gvi-admin",
      name: "Dr. Nadia Hassan",
      email: "admin@greenvalley.edu",
      password: "admin123",
      phone: "+1 555 0100",
      role: "org_admin",
      organization_id: "org-gvi",
      status: "active",
      locale: "en",
      default_identity_id: "id-gvi-clean",
      created_at: "2026-06-01T10:00:00Z",
    },
    {
      id: "t-omar",
      name: "Mr. Omar",
      email: "omar@greenvalley.edu",
      password: "teacher123",
      phone: "+1 555 0102",
      role: "teacher",
      organization_id: "org-gvi",
      status: "active",
      locale: "en",
      default_identity_id: null,
      created_at: "2026-06-10T09:00:00Z",
    },
    {
      id: "t-fatima",
      name: "Ms. Fatima",
      email: "fatima@greenvalley.edu",
      password: "teacher123",
      phone: "+1 555 0103",
      role: "teacher",
      organization_id: "org-gvi",
      status: "active",
      locale: "en",
      default_identity_id: null,
      created_at: "2026-06-12T09:00:00Z",
    },
    {
      id: "t-james",
      name: "Mr. James",
      email: "james@greenvalley.edu",
      password: "teacher123",
      phone: "+1 555 0104",
      role: "teacher",
      organization_id: "org-gvi",
      status: "active",
      locale: "en",
      default_identity_id: null,
      created_at: "2026-06-14T09:00:00Z",
    },
    {
      id: "t-sara",
      name: "Ms. Sara",
      email: "sara@greenvalley.edu",
      password: "teacher123",
      phone: "+1 555 0105",
      role: "teacher",
      organization_id: "org-gvi",
      status: "inactive",
      locale: "en",
      default_identity_id: null,
      created_at: "2026-06-18T09:00:00Z",
    },
    {
      id: "t-chen",
      name: "Ms. Chen",
      email: "chen@greenvalley.edu",
      password: "teacher123",
      phone: "+1 555 0106",
      role: "teacher",
      organization_id: "org-gvi",
      status: "active",
      locale: "en",
      default_identity_id: null,
      created_at: "2026-06-22T09:00:00Z",
    },
    {
      id: "t-layla",
      name: "Ms. Layla",
      email: "layla@inventors.academy",
      password: "teacher123",
      phone: "+1 555 0201",
      role: "org_admin",
      organization_id: "org-inventors",
      status: "active",
      locale: "en",
      default_identity_id: "id-kids-playful",
      created_at: "2026-06-16T09:00:00Z",
    },
    {
      id: "t-kai",
      name: "Mr. Kai",
      email: "kai@inventors.academy",
      password: "teacher123",
      phone: "+1 555 0202",
      role: "teacher",
      organization_id: "org-inventors",
      status: "inactive",
      locale: "en",
      default_identity_id: null,
      created_at: "2026-06-20T09:00:00Z",
    },
  ],
  platformAdmins: [
    {
      id: "pa-1",
      name: "Platform Admin",
      email: "admin@getxplain.ai",
      password: "admin123",
    },
  ],
  session: null,
  // Compat mirror — synced from logged-in user + org by the store
  teacher: {
    id: "t-salma",
    email: "salma@greenvalley.edu",
    display_name: "Ms. Salma",
    school_name: "Green Valley International",
    locale: "en",
    logo_data_url: null,
    default_identity_id: "id-gvi-clean",
  },
  identities: [
    {
      id: "id-gvi-clean",
      name: "Green Valley Clean",
      primary: "#7B4DFF",
      secondary: "#F5A623",
      background_style: "simple_white",
      image_style: "realistic",
      typography: "Nunito",
      instructions:
        "Simple white backgrounds. Clear hierarchy. Minimal decoration. Prefer realistic photos.",
      logo_data_url: null,
      created_at: "2026-07-01T09:00:00Z",
    },
    {
      id: "id-kids-playful",
      name: "Inventors Academy Kids",
      primary: "#2563EB",
      secondary: "#F97316",
      background_style: "solid_color",
      image_style: "cartoon",
      typography: "Nunito",
      instructions:
        "Solid color backgrounds OK. Large cartoon illustrations. Short friendly text. High contrast.",
      logo_data_url: null,
      created_at: "2026-07-05T09:00:00Z",
    },
    {
      id: "id-science-lab",
      name: "Science Lab Dark Accents",
      primary: "#0F766E",
      secondary: "#F59E0B",
      background_style: "simple_white",
      image_style: "diagram",
      typography: "Roboto",
      instructions:
        "White slides with teal accents. Prefer labelled scientific diagrams over photos. Dense but readable.",
      logo_data_url: null,
      created_at: "2026-07-10T09:00:00Z",
    },
  ],
  classes: [
    {
      id: "c-bio-a",
      name: "Grade 8 Bio (A)",
      grade: "Grade 8",
      curriculum: "British",
      description:
        "Introduction to cellular biology, ecosystems, and human anatomy. Standard curriculum alignment.",
      status: "active",
      accent: "#7B4DFF",
      created_at: "2026-07-10T09:00:00Z",
    },
    {
      id: "c-hist-b",
      name: "9th Grade History (B)",
      grade: "9th Grade",
      curriculum: "American",
      description:
        "World history spanning from early civilizations to the Renaissance period.",
      status: "active",
      accent: "#8B5CF6",
      created_at: "2026-07-08T09:00:00Z",
    },
    {
      id: "c-math-c",
      name: "Grade 12 Math (C)",
      grade: "Grade 12",
      curriculum: "IB Diploma",
      description:
        "Advanced calculus, trigonometry, and statistical analysis for college prep.",
      status: "active",
      accent: "#F59E0B",
      created_at: "2026-07-01T09:00:00Z",
    },
  ],
  media: [
    {
      id: "m-photo-pdf",
      display_name: "Photosynthesis_Advanced_Module.pdf",
      filename: "Photosynthesis_Advanced_Module.pdf",
      mime_type: "application/pdf",
      size_bytes: 4404019,
      status: "indexed",
      folder_id: "f-g8-a",
      uploaded_by: "Ms. Salma",
      description: "Unit PDF covering light reactions and Calvin cycle.",
      created_at: "2026-07-18T10:00:00Z",
    },
    {
      id: "m-photo-pptx",
      display_name: "Photosynthesis slides",
      filename: "Photosynthesis_Unit.pptx",
      mime_type:
        "application/vnd.openxmlformats-officedocument.presentationml.presentation",
      size_bytes: 13421772,
      status: "indexed",
      folder_id: "f-g8-a",
      uploaded_by: "Ms. Salma",
      description: "Core deck for Grade 8 bio.",
      created_at: "2026-07-17T14:00:00Z",
    },
    {
      id: "m-history",
      display_name: "Q3_History_Curriculum.pptx",
      filename: "Q3_History_Curriculum.pptx",
      mime_type:
        "application/vnd.openxmlformats-officedocument.presentationml.presentation",
      size_bytes: 13421772,
      status: "processing",
      folder_id: "f-g9-b",
      uploaded_by: "Ms. Salma",
      description: "",
      created_at: "2026-07-21T08:00:00Z",
    },
    {
      id: "m-quantum",
      display_name: "External Reading: Quantum Mechanics",
      filename: null,
      mime_type: "text/uri-list",
      size_bytes: 0,
      status: "failed",
      folder_id: "f-general",
      uploaded_by: "System Auto",
      description: "URL fetch failed.",
      error: "Could not fetch URL",
      created_at: "2026-07-15T11:00:00Z",
    },
    {
      id: "m-cell",
      display_name: "Cell_Division_Slides_Q1.pptx",
      filename: "Cell_Division_Slides_Q1.pptx",
      mime_type:
        "application/vnd.openxmlformats-officedocument.presentationml.presentation",
      size_bytes: 8912896,
      status: "indexed",
      folder_id: "f-g8-a",
      uploaded_by: "Ms. Salma",
      description: "",
      created_at: "2026-07-12T09:00:00Z",
    },
    {
      id: "m-algebra",
      display_name: "Algebra_Worksheet_Week2.pdf",
      filename: "Algebra_Worksheet_Week2.pdf",
      mime_type: "application/pdf",
      size_bytes: 1048576,
      status: "indexed",
      folder_id: "f-g9-b",
      uploaded_by: "Ms. Salma",
      description: "",
      created_at: "2026-07-11T09:00:00Z",
    },
    {
      id: "m-ai-intro",
      display_name: "Intro_to_AI_Unit.pdf",
      filename: "Intro_to_AI_Unit.pdf",
      mime_type: "application/pdf",
      size_bytes: 3145728,
      status: "indexed",
      folder_id: "f-g8-a",
      uploaded_by: "Ms. Salma",
      description: "Unit notes covering ML basics, ethics, and everyday AI examples.",
      created_at: "2026-07-19T10:00:00Z",
    },
    {
      id: "m-ai-slides",
      display_name: "AI_in_Everyday_Life.pptx",
      filename: "AI_in_Everyday_Life.pptx",
      mime_type:
        "application/vnd.openxmlformats-officedocument.presentationml.presentation",
      size_bytes: 8912896,
      status: "indexed",
      folder_id: "f-g8-a",
      uploaded_by: "Ms. Salma",
      description: "Slide deck with examples of AI in phones, maps, and recommendations.",
      created_at: "2026-07-19T11:00:00Z",
    },
    {
      id: "m-img-bookstore",
      display_name: "bookstore_front.jpg",
      filename: "bookstore_front.jpg",
      mime_type: "image/jpeg",
      size_bytes: 842112,
      status: "indexed",
      folder_id: "f-images",
      uploaded_by: "Ms. Salma",
      description: "Storefront photo for retail examples.",
      created_at: "2026-07-20T09:00:00Z",
    },
    {
      id: "m-img-diagram",
      display_name: "chloroplast_diagram.png",
      filename: "chloroplast_diagram.png",
      mime_type: "image/png",
      size_bytes: 512000,
      status: "indexed",
      folder_id: "f-images",
      uploaded_by: "Ms. Salma",
      description: "Labeled chloroplast diagram.",
      created_at: "2026-07-20T09:30:00Z",
    },
  ],
  folders: [
    { id: "f-images", name: "Images", kind: "images", updated_at: "2026-07-21T10:00:00Z" },
    { id: "f-g8-a", name: "Grade 8 - Set A", updated_at: "2026-07-19T10:00:00Z" },
    { id: "f-g9-b", name: "Grade 9 - Set B", updated_at: "2026-07-16T10:00:00Z" },
    { id: "f-g10", name: "Grade 10 - Core", updated_at: "2026-07-14T10:00:00Z" },
    { id: "f-general", name: "General Resources", updated_at: "2026-06-20T10:00:00Z" },
  ],
  lessons: [
    {
      id: "l-photo-ready",
      title: "Photosynthesis & Energy Transfer",
      class_id: "c-bio-a",
      status: "ready",
      icon: "science",
      updated_at: "2026-07-21T12:00:00Z",
      session_id: null,
      content: null,
    },
    {
      id: "l-ai-ready",
      title: "Introduction to AI",
      class_id: "c-bio-a",
      status: "ready",
      icon: "smart_toy",
      updated_at: "2026-07-20T15:00:00Z",
      session_id: null,
      content: null,
    },
    {
      id: "l-cells",
      title: "Cell Structure Basics",
      class_id: "c-bio-a",
      status: "ready",
      icon: "biotech",
      updated_at: "2026-07-18T10:00:00Z",
      session_id: null,
      content: null,
    },
    {
      id: "l-industrial",
      title: "The Industrial Revolution Impacts",
      class_id: "c-hist-b",
      status: "building",
      icon: "history_edu",
      updated_at: "2026-07-21T13:00:00Z",
      build_progress: { current: 3, total: 6, label: "Generating assets..." },
      session_id: null,
    },
    {
      id: "l-renaissance",
      title: "Renaissance Art & Ideas",
      class_id: "c-hist-b",
      status: "ready",
      icon: "palette",
      updated_at: "2026-07-19T11:00:00Z",
      session_id: null,
    },
    {
      id: "l-calc-fail",
      title: "Advanced Calculus Intro",
      class_id: "c-math-c",
      status: "failed",
      icon: "functions",
      updated_at: "2026-07-20T16:00:00Z",
      error: "Failed to parse PDF",
      session_id: null,
    },
    {
      id: "l-trig",
      title: "Trigonometry Review",
      class_id: "c-math-c",
      status: "ready",
      icon: "square_foot",
      updated_at: "2026-07-17T09:00:00Z",
      session_id: null,
    },
  ],
  sessions: [],
};

window.XplainSeed.planTemplate = {
  schema_version: "1.0",
  version: 1,
  title: "Lesson Plan: Introduction to Photosynthesis",
  class_ref: {
    id: "c-bio-a",
    name: "Grade 8 Bio (A)",
    grade: "Grade 8",
    curriculum: "British",
  },
  duration_minutes: 45,
  learning_styles: ["visual"],
  language: "en",
  media_ids: ["m-photo-pdf", "m-photo-pptx"],
  global_style: {
    id: "global-style",
    identity: "Green Valley International",
    colors: "Blue · Orange · White",
    typography: "Nunito",
    visual_style: "Realistic Images",
    rules: ["Large visuals", "Simple text", "Clear hierarchy"],
  },
  // pages = plan units (chat discovery model). sections kept as alias for built lesson.
  pages: [
    {
      id: "page-1",
      number: 1,
      type: "starter",
      title: "Page 1 — Hook",
      minutes: 10,
      status: "ready",
      body_md:
        "Begin by showing the first 2 minutes of Plant_Cell_Video. Ask students to observe leaf color and predict why they are green.",
      visual_note: "Opening photo of a sunlit leaf",
    },
    {
      id: "page-2",
      number: 2,
      type: "instruction",
      title: "Page 2 — Core Concept",
      minutes: 15,
      status: "ready",
      body_md:
        "Introduce the photosynthesis formula using Photosynthesis_Diagram.pdf. Break down inputs (Sunlight, CO2, Water) and outputs (Oxygen, Glucose).",
      visual_note: "Scientific diagram of the equation",
    },
    {
      id: "page-3",
      number: 3,
      type: "activity",
      title: "Page 3 — Hands-on Activity",
      minutes: 15,
      status: "ready",
      body_md:
        "Students work in pairs to recreate the photosynthesis diagram using construction paper cutouts representing molecules (H2O, CO2, etc.).",
      visual_note: "Step photos of the activity setup",
    },
    {
      id: "page-4",
      number: 4,
      type: "assessment",
      title: "Page 4 — Check Understanding",
      minutes: 5,
      status: "ready",
      body_md:
        "Exit ticket: Ask students to draw a quick sketch of a plant and label one input and one output of photosynthesis.",
      visual_note: "Simple exit-ticket card layout",
    },
  ],
  sources: [
    {
      media_asset_id: "m-photo-pptx",
      display_name: "Photosynthesis slides",
      refs: ["slide 3", "slide 12"],
    },
    {
      media_asset_id: "m-photo-pdf",
      display_name: "Photosynthesis_Advanced_Module.pdf",
      refs: ["page 4"],
    },
  ],
};

window.XplainSeed.lessonTemplate = {
  schema_version: "1.0",
  title: "Introduction to Photosynthesis",
  class_ref: {
    name: "Grade 8 Bio (A)",
    grade: "Grade 8",
    curriculum: "British",
  },
  duration_minutes: 45,
  objectives: [
    "Define photosynthesis and state its primary purpose in ecosystems.",
    "Identify the key inputs (reactants) and outputs (products) of the process.",
    "Explain the role of chlorophyll and sunlight in energy conversion.",
  ],
  learning_styles: ["visual", "kinesthetic"],
  sections: [
    {
      id: "starter",
      type: "starter",
      title: 'Starter Activity (10 mins): "Find Your Match"',
      minutes: 10,
      body_md:
        "**Setup:** Distribute index cards with terms: Water, Carbon Dioxide, Sunlight, Oxygen, Glucose, or Yields.\n\n**Action:** Students move silently to form groups representing the complete photosynthesis equation.\n\n**Debrief:** Winning group explains why their equation makes sense.",
      source: "Modified from general pedagogy practices",
    },
    {
      id: "teach-1",
      type: "instruction",
      title: "2. Core Concept: The Equation (15 mins)",
      minutes: 15,
      body_md:
        "Transition into a formal presentation of the chemical equation. Emphasize that matter is conserved, just rearranged.\n\n6CO₂ + 6H₂O + Light Energy → C₆H₁₂O₆ + 6O₂",
      has_diagram: true,
      source: "Slides 4-6, Photosynthesis slides",
    },
    {
      id: "activity-1",
      type: "activity",
      title: "3. Pair Diagram Activity (15 mins)",
      minutes: 15,
      body_md:
        "Pairs recreate the leaf diagram with labeled arrows for inputs and outputs using everyday classroom materials (paper, markers, tape).",
      source: "Adapted from Photosynthesis_Advanced_Module.pdf p.4",
    },
    {
      id: "assess",
      type: "assessment",
      title: "4. Exit Ticket (5 mins)",
      minutes: 5,
      body_md:
        "Sketch a plant. Label one input and one output of photosynthesis. Collect as students leave.",
      source: "Teacher-authored",
    },
  ],
  sources: [
    {
      media_asset_id: "m-photo-pptx",
      display_name: "Photosynthesis slides",
      refs: ["slide 3", "slide 12"],
    },
  ],
  slides: [
    {
      id: "s1",
      title: "Photosynthesis",
      subtitle: "Capturing Light to Build Life",
      section_id: "starter",
      status: "ready",
    },
    {
      id: "s2",
      title: "The Equation",
      subtitle: "Inputs → Outputs",
      section_id: "teach-1",
      status: "ready",
    },
    {
      id: "s3",
      title: "Find Your Match",
      subtitle: "Kinesthetic starter",
      section_id: "starter",
      status: "ready",
    },
    {
      id: "s4",
      title: "Leaf Diagram",
      subtitle: "Visual model",
      section_id: "teach-1",
      status: "ready",
    },
    {
      id: "s5",
      title: "Exit Ticket",
      subtitle: "Check for understanding",
      section_id: "assess",
      status: "ready",
    },
  ],
};